<?php

namespace Container2z7i8Md;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Am0XlM4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Am0XlM4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Am0XlM4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'tipoProductoRepository' => ['privates', 'App\\Repository\\TipoProductoRepository', 'getTipoProductoRepositoryService', true],
        ], [
            'paginator' => '?',
            'tipoProductoRepository' => 'App\\Repository\\TipoProductoRepository',
        ]);
    }
}
