<?php

namespace ContainerO7lX3mC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A2udkCNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A2udkCN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A2udkCN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tipoProducto' => ['privates', '.errored..service_locator.A2udkCN.App\\Entity\\TipoProducto', NULL, 'Cannot autowire service ".service_locator.A2udkCN": it references class "App\\Entity\\TipoProducto" but no such service exists.'],
        ], [
            'tipoProducto' => 'App\\Entity\\TipoProducto',
        ]);
    }
}
