<?php

namespace Container1siD1OX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CZvZ3FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CZvZ3_f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CZvZ3_f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tipoProductoRepository' => ['privates', 'App\\Repository\\TipoProductoRepository', 'getTipoProductoRepositoryService', true],
        ], [
            'tipoProductoRepository' => 'App\\Repository\\TipoProductoRepository',
        ]);
    }
}
