<?php

namespace ContainerHNrlTAl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CjbuZhFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CjbuZhF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CjbuZhF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['privates', '.errored.mum_6pB', NULL, 'Cannot determine controller argument for "App\\Controller\\TipoProductoController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "ContainerLxBLwph\\PaginatorInterface_82dac15".'],
            'tipoProductoRepository' => ['privates', 'App\\Repository\\TipoProductoRepository', 'getTipoProductoRepositoryService', true],
        ], [
            'paginator' => '?',
            'tipoProductoRepository' => 'App\\Repository\\TipoProductoRepository',
        ]);
    }
}
