<?php

namespace ContainerHNrlTAl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Mum6pBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.mum_6pB' shared service.
     *
     * @return \ContainerLxBLwph\PaginatorInterface_82dac15
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\TipoProductoController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "ContainerLxBLwph\\PaginatorInterface_82dac15".');
    }
}
