<?php

namespace Container8onpyF2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6Nnc05yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Nnc05y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Nnc05y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'repository' => ['privates', 'App\\Repository\\LocalidadRepository', 'getLocalidadRepositoryService', true],
        ], [
            'passwordEncoder' => '?',
            'repository' => 'App\\Repository\\LocalidadRepository',
        ]);
    }
}
