<?php

namespace ContainerK2YYDOd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QW1BMvAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QW1BMvA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QW1BMvA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mensajeRepository' => ['privates', 'App\\Repository\\MensajeRepository', 'getMensajeRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'mensajeRepository' => 'App\\Repository\\MensajeRepository',
            'paginator' => '?',
        ]);
    }
}
