<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKlWTX8F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKlWTX8F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKlWTX8F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKlWTX8F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKlWTX8F\App_KernelDevDebugContainer([
    'container.build_hash' => 'KlWTX8F',
    'container.build_id' => '195924bc',
    'container.build_time' => 1612700502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKlWTX8F');
