<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXFsoxZx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXFsoxZx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXFsoxZx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXFsoxZx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXFsoxZx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XFsoxZx',
    'container.build_id' => '693c09c0',
    'container.build_time' => 1612983463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXFsoxZx');
