<?php

namespace ContainerC7Q5Oma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GQnSgGzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GQnSgGz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GQnSgGz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'imgs' => ['privates', 'App\\Repository\\ImgProductoRepository', 'getImgProductoRepositoryService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
        ], [
            'imgs' => 'App\\Repository\\ImgProductoRepository',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
        ]);
    }
}
