<?php

namespace ContainerGpUxnxm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_52xk0EgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.52xk0Eg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.52xk0Eg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'provinciaRepository' => ['privates', 'App\\Repository\\ProvinciaRepository', 'getProvinciaRepositoryService', true],
        ], [
            'paginator' => '?',
            'provinciaRepository' => 'App\\Repository\\ProvinciaRepository',
        ]);
    }
}
